Import("env")

src = Split("""adler32.c compress.c crc32.c deflate.c gzio.c
infback.c inffast.c inflate.c inftrees.c trees.c uncompr.c
zutil.c""")

src.append("win32/zlib.def")
zlib = env.SharedLibrary("zlib1", source=src)
env.Install(env["libdir"], zlib)
env.Install(env["includedir"], ["zlib.h", "zconf.h"])
